// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $ArticleSlider from "./islands/ArticleSlider.tsx";
import * as $BannerSlider from "./islands/BannerSlider.tsx";
import * as $ProductShelf from "./islands/ProductShelf.tsx";
import * as $BannerSliderMedia from "./islands/BannerSliderMedia.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/ArticleSlider.tsx": $ArticleSlider,
    "./islands/BannerSlider.tsx": $BannerSlider,
    "./islands/ProductShelf.tsx": $ProductShelf,
    "./islands/BannerSliderMedia.tsx": $BannerSliderMedia,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
