// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AmbassadorSlider from "./islands/AmbassadorSlider.tsx";
import * as $ArticleSlider from "./islands/ArticleSlider.tsx";
import * as $BannerSlider from "./islands/BannerSlider.tsx";
import * as $BlogArticlesSliderIsland from "./islands/BlogArticlesSliderIsland.tsx";
import * as $BreadcrumbIsland from "./islands/BreadcrumbIsland.tsx";
import * as $CustomInfoCardSlider from "./islands/CustomInfoCardSlider.tsx";
import * as $FoldItemsIsland from "./islands/FoldItemsIsland.tsx";
import * as $InfoCardSlider from "./islands/InfoCardSlider.tsx";
import * as $ProductShelf from "./islands/ProductShelf.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AmbassadorSlider.tsx": $AmbassadorSlider,
    "./islands/ArticleSlider.tsx": $ArticleSlider,
    "./islands/BannerSlider.tsx": $BannerSlider,
    "./islands/BlogArticlesSliderIsland.tsx": $BlogArticlesSliderIsland,
    "./islands/BreadcrumbIsland.tsx": $BreadcrumbIsland,
    "./islands/CustomInfoCardSlider.tsx": $CustomInfoCardSlider,
    "./islands/FoldItemsIsland.tsx": $FoldItemsIsland,
    "./islands/InfoCardSlider.tsx": $InfoCardSlider,
    "./islands/ProductShelf.tsx": $ProductShelf,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
