// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$0 from "./loaders/customVTEX/productById.ts";
import * as $$$$$$0 from "./sections/Logos.tsx";
import * as $$$$$$1 from "./sections/Lps/AmbassadorsSection.tsx";
import * as $$$$$$2 from "./sections/Lps/ArticleFrigidaireSection.tsx";
import * as $$$$$$3 from "./sections/Lps/ArticleGridSection.tsx";
import * as $$$$$$4 from "./sections/Lps/ArticleResponsiveGridSection.tsx";
import * as $$$$$$5 from "./sections/Lps/ArticleSliderSection.tsx";
import * as $$$$$$6 from "./sections/Lps/BannerMediaSection.tsx";
import * as $$$$$$7 from "./sections/Lps/BannerSliderSection.tsx";
import * as $$$$$$8 from "./sections/Lps/CategoriesSection.tsx";
import * as $$$$$$9 from "./sections/Lps/DimmedColorsSection.tsx";
import * as $$$$$$10 from "./sections/Lps/FeatureHighlightSection.tsx";
import * as $$$$$$11 from "./sections/Lps/FinalCtaWithCardsSection.tsx";
import * as $$$$$$12 from "./sections/Lps/FooterFrigidaireLogoSection.tsx";
import * as $$$$$$13 from "./sections/Lps/ImageCollectionGridSection.tsx";
import * as $$$$$$14 from "./sections/Lps/ImageGridSection.tsx";
import * as $$$$$$15 from "./sections/Lps/ImageTextCardGridSection.tsx";
import * as $$$$$$16 from "./sections/Lps/ImageWithTextColumnsSection.tsx";
import * as $$$$$$17 from "./sections/Lps/InfoCardCustomBgSection.tsx";
import * as $$$$$$18 from "./sections/Lps/InfoCardSection.tsx";
import * as $$$$$$19 from "./sections/Lps/MailingProductSection.tsx";
import * as $$$$$$20 from "./sections/Lps/MultiImageBannerSection.tsx";
import * as $$$$$$21 from "./sections/Lps/PdfWithTextSection.tsx";
import * as $$$$$$22 from "./sections/Lps/ReviewsSliderSection.tsx";
import * as $$$$$$23 from "./sections/Lps/TextSection.tsx";
import * as $$$$$$24 from "./sections/Lps/TitleFrigidaireSection.tsx";
import * as $$$$$$25 from "./sections/Lps/VideoWithCtaSection.tsx";
import * as $$$$$$26 from "./sections/Product/ProductMediaSection.tsx";
import * as $$$$$$27 from "./sections/Product/ProductMediaSideBySideSection.tsx";
import * as $$$$$$28 from "./sections/Product/ProductShelfSection.tsx";
import * as $$$$$$29 from "./sections/Product/ProductShelfWithComparatorSection.tsx";
import * as $$$$$$30 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/customVTEX/productById.ts": $$$0,
  },
  "sections": {
    "site/sections/Logos.tsx": $$$$$$0,
    "site/sections/Lps/AmbassadorsSection.tsx": $$$$$$1,
    "site/sections/Lps/ArticleFrigidaireSection.tsx": $$$$$$2,
    "site/sections/Lps/ArticleGridSection.tsx": $$$$$$3,
    "site/sections/Lps/ArticleResponsiveGridSection.tsx": $$$$$$4,
    "site/sections/Lps/ArticleSliderSection.tsx": $$$$$$5,
    "site/sections/Lps/BannerMediaSection.tsx": $$$$$$6,
    "site/sections/Lps/BannerSliderSection.tsx": $$$$$$7,
    "site/sections/Lps/CategoriesSection.tsx": $$$$$$8,
    "site/sections/Lps/DimmedColorsSection.tsx": $$$$$$9,
    "site/sections/Lps/FeatureHighlightSection.tsx": $$$$$$10,
    "site/sections/Lps/FinalCtaWithCardsSection.tsx": $$$$$$11,
    "site/sections/Lps/FooterFrigidaireLogoSection.tsx": $$$$$$12,
    "site/sections/Lps/ImageCollectionGridSection.tsx": $$$$$$13,
    "site/sections/Lps/ImageGridSection.tsx": $$$$$$14,
    "site/sections/Lps/ImageTextCardGridSection.tsx": $$$$$$15,
    "site/sections/Lps/ImageWithTextColumnsSection.tsx": $$$$$$16,
    "site/sections/Lps/InfoCardCustomBgSection.tsx": $$$$$$17,
    "site/sections/Lps/InfoCardSection.tsx": $$$$$$18,
    "site/sections/Lps/MailingProductSection.tsx": $$$$$$19,
    "site/sections/Lps/MultiImageBannerSection.tsx": $$$$$$20,
    "site/sections/Lps/PdfWithTextSection.tsx": $$$$$$21,
    "site/sections/Lps/ReviewsSliderSection.tsx": $$$$$$22,
    "site/sections/Lps/TextSection.tsx": $$$$$$23,
    "site/sections/Lps/TitleFrigidaireSection.tsx": $$$$$$24,
    "site/sections/Lps/VideoWithCtaSection.tsx": $$$$$$25,
    "site/sections/Product/ProductMediaSection.tsx": $$$$$$26,
    "site/sections/Product/ProductMediaSideBySideSection.tsx": $$$$$$27,
    "site/sections/Product/ProductShelfSection.tsx": $$$$$$28,
    "site/sections/Product/ProductShelfWithComparatorSection.tsx": $$$$$$29,
    "site/sections/Theme/Theme.tsx": $$$$$$30,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
