// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$0 from "./loaders/customVTEX/productById.ts";
import * as $$$$$$0 from "./sections/Logos.tsx";
import * as $$$$$$1 from "./sections/Lps/EcoPlus/ArticleSliderSection.tsx";
import * as $$$$$$2 from "./sections/Lps/EcoPlus/BannerMediaSection.tsx";
import * as $$$$$$3 from "./sections/Lps/EcoPlus/BannerSliderSection.tsx";
import * as $$$$$$4 from "./sections/Lps/EcoPlus/CategoriesSection.tsx";
import * as $$$$$$5 from "./sections/Lps/EcoPlus/ImageWithTextColumnsSection.tsx";
import * as $$$$$$6 from "./sections/Lps/EcoPlus/InfoCardSection.tsx";
import * as $$$$$$7 from "./sections/Lps/EcoPlus/ReviewsSliderSection.tsx";
import * as $$$$$$8 from "./sections/Lps/Homepedia/ArticleSliderHomeSection.tsx";
import * as $$$$$$9 from "./sections/Lps/Homepedia/BannerSliderHomeSection.tsx";
import * as $$$$$$10 from "./sections/Lps/Homepedia/TextSection.tsx";
import * as $$$$$$11 from "./sections/Product/ProductShelfSection.tsx";
import * as $$$$$$12 from "./sections/Product/ProductShelfWithComparatorSection.tsx";
import * as $$$$$$13 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/customVTEX/productById.ts": $$$0,
  },
  "sections": {
    "site/sections/Logos.tsx": $$$$$$0,
    "site/sections/Lps/EcoPlus/ArticleSliderSection.tsx": $$$$$$1,
    "site/sections/Lps/EcoPlus/BannerMediaSection.tsx": $$$$$$2,
    "site/sections/Lps/EcoPlus/BannerSliderSection.tsx": $$$$$$3,
    "site/sections/Lps/EcoPlus/CategoriesSection.tsx": $$$$$$4,
    "site/sections/Lps/EcoPlus/FakeReviewSection.tsx": $$$$$$5,
    "site/sections/Lps/EcoPlus/ImageWithTextColumnsSection.tsx": $$$$$$6,
    "site/sections/Lps/EcoPlus/InfoCardSection.tsx": $$$$$$7,
    "site/sections/Product/ProductShelfSection.tsx": $$$$$$8,
    "site/sections/Theme/Theme.tsx": $$$$$$9,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
